import {getStore,getDeployStore} from '@netlify/blobs';
const ALLOWED=new Set(['landing_view','eligibility_complete','qualification_complete','broker_route','affiliate_click','telegram_join_click','whatsapp_join_click']);
const clean=(v,n=100)=>String(v??'').replace(/[<>\r\n]/g,' ').slice(0,n);\nconst RATE_WINDOW_MS=60*1000,MAX_EVENTS_PER_VISITOR=30;
const VALID_MARKETS=new Set(['synthetic','forex_gold','undecided','']);const VALID_BROKERS=new Set(['deriv','hfm','']);const VALID_ELIGIBLE=new Set(['yes','no','']);
const isProd=()=>Netlify.context?.deploy?.context==='production';
const storeFor=name=>isProd()?getStore(name):getDeployStore(name);
export default async(req)=>{if(req.method!=='POST')return new Response('Method not allowed',{status:405});let b;try{b=await req.json()}catch{return new Response('Bad JSON',{status:400})}if(!ALLOWED.has(b.event))return new Response('Invalid event',{status:400});const visitorId=clean(b.visitorId,80);if(!visitorId)return new Response('Missing visitor',{status:400});const eligible=clean(b.props?.eligible),market=clean(b.props?.market),broker=clean(b.props?.broker);if(!VALID_ELIGIBLE.has(eligible)||!VALID_MARKETS.has(market)||!VALID_BROKERS.has(broker))return new Response('Invalid properties',{status:400});const store=storeFor('rae-events');const now=Date.now();const recentKey='rate-'+visitorId;const recent=await store.get(recentKey,{type:'json'}).catch(()=>null);if(recent&&now-recent.start<RATE_WINDOW_MS&&recent.count>=MAX_EVENTS_PER_VISITOR)return new Response('Too many events',{status:429});const next=recent&&now-recent.start<RATE_WINDOW_MS?{start:recent.start,count:recent.count+1}:{start:now,count:1};await store.setJSON(recentKey,next);
const e={event:b.event,visitorId:clean(b.visitorId,80),utm:{source:clean(b.utm?.source),medium:clean(b.utm?.medium),campaign:clean(b.utm?.campaign),content:clean(b.utm?.content)},props:{eligible,market,broker},ts:new Date().toISOString()};await store.setJSON(`event-${Date.now()}-${crypto.randomUUID()}`,e);return new Response(null,{status:202})};
export const config={path:'/api/events'};
