const LINKS={deriv:'https://t.deriv.link?t=N4YTBACHU9HN',hfm:'https://www.hfm.com/sv/en/?refid=30477807'};
const qs=new URLSearchParams(location.search);const vid=localStorage.rae_vid||(localStorage.rae_vid=crypto.randomUUID());
const utm={source:qs.get('utm_source')||'direct',medium:qs.get('utm_medium')||'none',campaign:qs.get('utm_campaign')||'none',content:qs.get('utm_content')||'none'};
async function track(event,props={}){try{await fetch('/api/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event,visitorId:vid,utm,props})})}catch{}}
track('landing_view');
const eligibilityMsg=document.querySelector('#eligibilityMsg'),qualification=document.querySelector('#qualification'),result=document.querySelector('#result'),routes=document.querySelector('#routes');
document.querySelectorAll('.eligibility-choice').forEach(b=>b.onclick=()=>{const ok=b.dataset.eligible==='yes';track('eligibility_complete',{eligible:ok?'yes':'no'});if(ok){qualification.hidden=false;eligibilityMsg.hidden=true;qualification.scrollIntoView({behavior:'smooth'});}else{qualification.hidden=true;result.hidden=true;eligibilityMsg.hidden=false;document.querySelector('.dark').scrollIntoView({behavior:'smooth'});}});
document.querySelectorAll('#qualification .choice').forEach(b=>b.onclick=()=>{const m=b.dataset.market;track('qualification_complete',{market:m});result.hidden=false;routes.innerHTML='';const add=(broker,label,desc)=>{const a=document.createElement('a');a.className='broker';a.href=LINKS[broker];a.target='_blank';a.rel='noopener noreferrer sponsored';a.innerHTML=`<div>${label}<small>${desc}</small></div><span class="arrow">→</span>`;a.onclick=()=>track('affiliate_click',{broker,market:m});routes.appendChild(a)};if(m==='synthetic')add('deriv','Découvrir Deriv','Indices synthétiques — vérifiez disponibilité et conditions.');if(m==='forex_gold')add('hfm','Découvrir HFM','Forex & Or — vérifiez disponibilité et conditions.');if(m==='undecided'){add('deriv','Comparer Deriv','Option indices synthétiques.');add('hfm','Comparer HFM','Option Forex & Or.')}track('broker_route',{market:m});result.scrollIntoView({behavior:'smooth'});});
document.querySelector('#telegram').onclick=()=>track('telegram_join_click');document.querySelector('#whatsapp').onclick=()=>track('whatsapp_join_click');
if(location.hash==='#admin')document.querySelector('#admin').hidden=false;
window.raeAdmin=async()=>{const t=document.querySelector('#token').value;sessionStorage.rae_token=t;const r=await fetch('/api/summary',{headers:{authorization:`Bearer ${t}`}});if(!r.ok){document.querySelector('#adminmsg').textContent='Accès refusé.';return}const d=await r.json();document.querySelector('#dashboard').hidden=false;document.querySelector('#kpiVisitors').textContent=d.visitors;document.querySelector('#kpiQualified').textContent=d.qualified;document.querySelector('#kpiClicks').textContent=d.affiliateClicks;document.querySelector('#kpiCommission').textContent='$'+d.commission.toFixed(2);document.querySelector('#rate1').textContent=d.visitors?Math.round(d.qualified/d.visitors*100)+'%':'—';document.querySelector('#rate2').textContent=d.qualified?Math.round(d.affiliateClicks/d.qualified*100)+'%':'—';document.querySelector('#raw').textContent=JSON.stringify(d,null,2)};
window.raeBusiness=async()=>{const t=sessionStorage.rae_token||document.querySelector('#token').value;const event=document.querySelector('#bevent').value,broker=document.querySelector('#bbroker').value,amount=Number(document.querySelector('#bamount').value||0),note=document.querySelector('#bnote').value;const r=await fetch('/api/business-events',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${t}`},body:JSON.stringify({event,broker,amount,note})});document.querySelector('#adminmsg').textContent=r.ok?'Enregistré.':'Erreur / accès refusé.';if(r.ok)raeAdmin()};
